name: 'Waka - Readme'
author: Athil Cyriac Ajay
description: 'Add a Wakatime Coding Activity graph in your Readme'

inputs:
  GH_TOKEN:
    description: 'GitHub access token with Repo scope'
    required: true
    default: ${{ github.token }}

  WAKATIME_API_KEY:
    description: 'Your Wakatime API Key'
    required: true

  USERNAME:
    description: 'Your GitHub username'
    default: ${{ github.repository_owner }}
    required: false

  SHOW_TITLE:
    description: "Displays the week number and days in Readme as title"
    default: false
    required: false


runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'info'
  color: 'blue'