name: "Waka - Readme"
author: Athil Cyriac Ajay
description: "Add a Wakatime Coding Activity graph in your Readme"

inputs:
  GH_TOKEN:
    description: "GitHub access token with Repo scope"
    required: true
    default: ${{ github.token }}

  WAKATIME_API_KEY:
    description: "Your Wakatime/Wakapi/Hakatime API Key"
    required: true

  API_BASE_URL:
    description: "Aternative API base URL when using a third-party WakaTime backend"
    default: "https://wakatime.com/api"
    required: false

  REPOSITORY:
    description: "Your GitHub repository"
    default: ${{ github.repository }}
    required: false

  SHOW_TITLE:
    description: "Displays the week number and days in Readme as title"
    default: false
    required: false

  COMMIT_MESSAGE:
    description: "Add a commit message of your choice"
    default: "Updated the Graph with new Metrics"
    required: false

  BLOCKS:
    description: "Add the progress blocks of your choice"
    default: "░▒▓█"
    required: false

  SHOW_TIME:
    description: "Displays the amount of time spent in each language"
    default: true
    required: false

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "info"
  color: "blue"
